### ISSUE TITLE
Bootstrap v5.1.2 compile error

### ISSUE THREAD

**Issue by tim-breitenstein-it** [patriceckhart/NeosRulez.DynamicResources#2]
Using the latest Bootstrap v5.1.2 gives me 2 compiling error:

`expecting color, null received: /var/www/neos.dev/Packages/Sites/Raw.Site/Resources/Private/Styles/scss/mixins/_table-variants.scss on line 5, at column 5`

`expecting color, null received: /var/www/neos.dev/Packages/Sites/Raw.Site/Resources/Private/Styles/scss/mixins/_buttons.scss on line 41, at column 7`

If I comment these 2 line out:

```
// @import "tables";
// @import "buttons";
```
it works.

Maybe the same: https://github.com/scssphp/scssphp/issues/434 or https://github.com/scssphp/scssphp/issues/440

Can you please update **scssphp/scssphp** to the latest version?

**Comment by patriceckhart** [comment]
I set it to scssphp/scssphp: ^ 1.8. I hope it helps?

**Comment by tim-breitenstein-it** [comment]
Thx!
