### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by bbtimx** [patriceckhart/NeosRulez.DynamicResources#3]
I moved my Neos development instance to my production environment.

Edit my .htaccess
`setEnv FLOW_CONTEXT Production`

Everything runs fine but I think NeosRulez.DynamicResources still compile the Bootstrap SCSS code on every page view and therefore the page ist very slow.

How is it possible to prevent compiling CSSC code and use the minified result on production mode?

**Comment by patriceckhart** [comment]
The condition: `$_ENV['FLOW_CONTEXT'] == 'Production'`. But other guys have had problems with this. Try to empty your flow cache once with `FLOW_CONTEXT=Production ./flow flow:cache:flush --force`

**Comment by bbtimx** [comment]
> The condition: $_ENV['FLOW_CONTEXT'] == 'Production'. But other guys have had problems with this. Try to empty your flow cache once with FLOW_CONTEXT=Production ./flow flow:cache:flush --force

Tryed this, but I still  have a load time of about 9s for style.min.css .

**Comment by patriceckhart** [comment]
What is the file size of your styles.min.css? Can you send me your production url?

**Comment by bbtimx** [comment]
> What is the file size of your styles.min.css? Can you send me your production url?

I have sent you an email with the url.
